security:
    providers:
        eulogin:
            id: eulogin.userprovider
    firewalls:
        default:
            guard:
                provider: eulogin
                entry_point: eulogin.userprovider
